language: node_js
node_js:
  - "8"
#setting up VM
before_install:
#activities to be performed during building
jobs:
  include:
    -stage: before_install
    #install necessary node modules
    script: npm install
    -stage: lint
    #lint all html files in tree
    script: node node_modules/.bin/htmllint ./www/**/*index.html
