language: node_js
node_js:
  - "8"

#do before testing
before_script:
    #install necessary node modules
    - "npm install htmllint eslint"

#lint all html files in tree
script:
  - "./node_modules/.bin/htmllint ./www/**/*.html"
  - "./node_modules/.bin/eslint ./www/**/*.js"
