language: node_js
node_js:
  - "8"
#setting up VM
before_install:
    #install necessary node modules
    -npm install htmllint
#activities to be performed during building
jobs:
  include:
    -stage: lint_html
      name: "Linting HTML"
      #lint all html files in tree
      script: ./node_modules/.bin/htmllint ./www/**/*index.html
