language: node_js
rvm:
#setting up VM
before_install:
  - sudo apt-get install -y nodejs
  - sudo npm install -g htmllint-cli
#activities to be performed during building
jobs:
  include:
    -stage: lint
    #lint all html files in tree
    script: nodejs htmllint .www/**/*index.html
