language: node_js
rvm:
#activities to be performed during building
jobs:
  include:
    -stage: lint
    #lint all html files in tree
    script: nodejs node_modules/htmllint-cli/bin/cli.js .www/**/*index.html
