language: node_js
node_js:
  - "8"
#setting up VM
before_install:
#activities to be performed during building
jobs:
  include:
    -stage: before_install
    #install necessary node modules
    script: npm install
    -stage: lint_html
      name: "Linting HTML"
      #lint all html files in tree
      script: . node_modules/.bin/htmllint ./www/**/*index.html
    -stage: lint_JS
      name: "Linting JS"
      #lint all js files in tree
      script: ./node_modules/.bin/eslint ./www/**/*.js
    -stage: lint_css
      name: "Linting CSS"
      #lint all js files in tree
      script: ./node_modules/.bin/stylelint ./www/**/*.css

